const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0VHemVZOXJFSHdwVklnUWFNVVc4MWo2dWc5TmNNSU4yd0ZucEhLRHNtbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0REdlpuOFc3dXNrbHp2MmlLZm5HaFR6dk5wcWJtK1FWYURrT1NNQlRDYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4UGlSeWd6VDd4TUZzRzAvZmdYakVaVXFBRlJ5NWFPTjRPSW1LYmVlT0Y4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRZThSeTBSR1AyeVhoK2sxREc4aXBJcXVGckZXWmtUbTRpUVhCWmsxcnhrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklEUlNzK0NTZVUvMHI0OHhYQktmWUp1Z1QwVTlGVzkxOTh3eUZIOHovRnc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlpRFczcEV4Qk9XN1piTXoyTmgwZmI3dG1vOG5nTE1JemZJZVFsZTMzdzg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUpiWHYxVExKR3k0dlZWZUpHdnZwY29WYjFVeVdvaFdvN0dCdS94eDlYWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiamdBNTg2L3BQTU8xUi9CLzdxdVczQ2wyNjJtTkNFT1VjdWFZSjVGSGlUaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1vLzZsL3RrT1JEL1AzUkw0Q0gzYkk2R2pEbXpVby9Tb0x5anRNRnlLY2JZdGdPN2ErNnVETmJSZ1NzREExWXdHbzdJaDNrditKY2Qzclowb1U5cmpRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NzcsImFkdlNlY3JldEtleSI6ImVtYnAyY09PcWF0YW4xTFA1R04zRzBuZEs3azlnNWFrVTZNc3ZQSDMvZjg9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IlBWamJnN0d2VEFlM1NSNG1QTl9DRGciLCJwaG9uZUlkIjoiZjJlNmQ3OTAtYWNjOC00YjE4LTg3MzYtZjAxZWYzN2ZhNTkwIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im5QVm5LZHhBNEY1UkNsL0tHek1ZbUJweVByYz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLYTF4N2ZOSEk3ZjAxMk5wUWtaUndoR241WkE9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiTVJNQUxWSU4iLCJtZSI6eyJpZCI6IjI1NTYyMjczMTMxMTo4QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjY2MTc2NDU0MjIxOTc3OjhAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMKyt0NmtCRU1URjhjY0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJBWG4xUFB6c1R6NVE3U0xCeWxJSnFTMEVQbmJaQWZJbXZvd0RHcDNiOTNnPSIsImFjY291bnRTaWduYXR1cmUiOiIyYnljd2NmRzlqMnVsUVVyaDd1V0lGYkwwell6azUrZ3ZUa09OcFdweXZiK3kwUkZCM0hRNjJYV2xjcDZoUlUrR0ZaN09nVzJmMnVwbFhWbXRtOXVBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoibmY2cFh1SVplR29jVURLUElTVCtzRGJZeVFYc3c1cWdVcUl1YmV4dDF2V2d3NFB6TTVxZUM5TUE2cXJ0dmVMQVArSWMzbDJnZGVvdW1NajM4SEZnaEE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTU2MjI3MzEzMTE6OEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJRRjU5VHo4N0U4K1VPMGl3Y3BTQ2FrdEJENTIyUUh5SnI2TUF4cWQyL2Q0In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWtJQlE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NjEzNzA4MzQsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSy9aIn0=": process.env.SESSION_ID || "",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
